version: "3"
services:
  s1:
    build:
      context: ./s1
    ports:
      - "8081:8081"
    networks:
      - my-network

  s2:
    build:
      context: ./s2
    ports:
      - "8082:8082"
    networks:
      - my-network

  s3:
    build:
      context: ./s3
    ports:
      - "8083:8083"    
    depends_on:
      - s1
      - s2
    networks:
      - my-network

networks:
  my-network:

