name: Bump Node.js version on master push

on:
  push:
    branches:
      - master

jobs: 
  bump-node-version:
    runs-on: ubuntu-latest

    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: set up Node.js
        uses: action/setup-node@v2
        with:
          node-version: 14  #set your desired Node.js version here

      - name: Install Dependencies
        run: npm install  #or yarn install, depending on your project setup
      - name: Bump Node.js version
        run: |
          #you can use a tool like 'nvm' or 'n' to bump Node.js verison
          # Example using 'n' to bump to the latest LTS version

          n lts
      - name: commit and push bumped Node.js version
        run: |
          git config --global user.name "Harsha Vardhan"
          git config --global user.email "harshavardhan@gmail.com"
          git add .nvmrc  # Assuming you store Node.js version on a .nvmrc file
          git commit -m "Bump Node.js version"
          git push
