name: Bump Node.js Version

on:
  push:
    branches:
      - master

jobs:
  bump-node-version:
    runs-on: ubuntu-latest

    steps:
    - name: Check if it's a master branch push
      run: |
        if [[ "$GITHUB_REF" != "refs/heads/master" ]]; then
          echo "This is not the master branch. Exiting..."
          exit 0
        fi

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Bump Node.js version
      run: |
        # Your code to bump Node.js version goes here
        # For example, you can use nvm to switch Node.js versions:
        nvm install 16
        nvm use 16

    - name: Install Dependencies and Build
      run: |
        cd s3/app.js  # Replace with the actual path to your project directory
        npm install
        npm run build
